package frc.robot.subsystems;

import static edu.wpi.first.units.Units.Degrees;
import static edu.wpi.first.units.Units.DegreesPerSecond;
import static edu.wpi.first.units.Units.Inches;
import static edu.wpi.first.units.Units.Meters;
import static edu.wpi.first.units.Units.Pounds;
import static edu.wpi.first.units.Units.Radians;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.Seconds;

import java.io.IOException;
import java.util.Optional;
import java.util.function.Supplier;

import org.json.simple.parser.ParseException;
import org.littletonrobotics.junction.Logger;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import frc.robot.Constants;
import frc.robot.Robot;
import frc.robot.RobotState;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.vision.LimelightHelpers;
import frc.robot.subsystems.vision.VisionChassisSubsystem;
import frc.robot.subsystems.vision.VisionTurretSubsystem;
import frc.robot.util.LoggedTunableNumber;
import frc.robot.util.sim.MapleSimSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class Swerve extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;
    private VisionTurretSubsystem limelightTurret;
    private VisionChassisSubsystem limelightChassis;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    Slot0Configs testConfigs = new Slot0Configs();
    Slot0Configs readConfigs = new Slot0Configs();
    public boolean testConfigsChanged = false;

    LoggedTunableNumber kP = new LoggedTunableNumber("Pose/DrivekP", 0.34);
    LoggedTunableNumber kI = new LoggedTunableNumber("Pose/DrivekI", 0.0);
    LoggedTunableNumber kD = new LoggedTunableNumber("Pose/DrivekD", 0.0);
    LoggedTunableNumber kS = new LoggedTunableNumber("Pose/DrivekS", 0.16);
    LoggedTunableNumber kV = new LoggedTunableNumber("Pose/DrivekV", 0.11);
    LoggedTunableNumber kA = new LoggedTunableNumber("Pose/DrivekA", 0.0);

    LoggedTunableNumber n1 = new LoggedTunableNumber("PoseVisionMatrix/n1", 1.25);
    LoggedTunableNumber n2 = new LoggedTunableNumber("PoseVisionMatrix/n2", 1.25);
    LoggedTunableNumber n3 = new LoggedTunableNumber("PoseVisionMatrix/gyro", Double.MAX_VALUE);


    private double visionTimeStampTurret;
    private double visionTimeStampChassis;
    private Matrix<N3, N1> visionSTDMatrixTurret = VecBuilder.fill(1.25, 1.25, Double.MAX_VALUE);
    private Matrix<N3, N1> visionSTDMatrixChassis = VecBuilder.fill(n1.get(), n2.get(), n3.get());
    // private Matrix<N3, N1> visionSTDMatrix = VecBuilder.fill();

    // LimelightHelpers.LimelightResults turretLimelightResults = LimelightHelpers.getLatestResults(Constants.VisionConstants.kTurretLimelight);
    private RobotState robotState = RobotState.getInstance();

    private ChassisSpeeds fieldRelativeChassisSpeeds = new ChassisSpeeds();

    private Field2d field2d = new Field2d();


    private Pose3d testCameraPose;
    
    @Override
    public void periodic() {
        // turretLimelightResults = LimelightHelpers.getLatestResults(Constants.VisionConstants.kTurretLimelight);

        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
                setOperatorPerspectiveForward(
                    Constants.getAllianceColor() == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
        }

        // visionTurretTimeStamp = robotState.getMegaTag1TimeStamp();
        visionTimeStampTurret = robotState.getMegaTag2TimeStampTurret();
        visionTimeStampChassis = robotState.getMegaTag2TimeStampChassis();

        LimelightHelpers.SetRobotOrientation(
            Constants.VisionConstants.kTurretLimelight, 
            // MathUtil.inputModulus(getState().Pose.getRotation().getDegrees(), 0, 360),
            getState().Pose.getRotation().getDegrees(),
            RadiansPerSecond.of(getState().Speeds.omegaRadiansPerSecond).in(DegreesPerSecond), 
            0,
            0, 
            0, 
            0
        );
        LimelightHelpers.SetRobotOrientation(
            Constants.VisionConstants.kChassisLimelight, 
            // MathUtil.inputModulus(getState().Pose.getRotation().getDegrees(), 0, 360),
            getState().Pose.getRotation().getDegrees(),
            RadiansPerSecond.of(getState().Speeds.omegaRadiansPerSecond).in(DegreesPerSecond), 
            0,
            0, 
            0, 
            0
        );

        LimelightHelpers.setCameraPose_RobotSpace(
            Constants.VisionConstants.kTurretLimelight, 
            robotState.getRobotToLimelight().getMeasureX().in(Meters), 
            -robotState.getRobotToLimelight().getMeasureY().in(Meters), 
            robotState.getRobotToLimelight().getMeasureZ().in(Meters), 
            0,
            Radians.of(robotState.getRobotToLimelight().getRotation().getY()).in(Degrees),
            Radians.of(robotState.getRobotToLimelight().getRotation().getZ()).in(Degrees)    
        );
        // LimelightHelpers.setCameraPose_RobotSpace(
        //     Constants.VisionConstants.kChassisLimelight, 
        //     Inches.of(-4.98 + 0).in(Meters), 
        //     Inches.of(-14.16).in(Meters), 
        //     Inches.of(13.44).in(Meters), 
        //     -2,
        //     15,
        //     90
        // );




        boolean didItWork = false;
  
        if(limelightTurret.inputs.tv) {
            addVisionMeasurement(
                robotState.getTurretLimelightMegaTag2(), 
                // robotState.getTurretLimelightPose2d(), 
                visionTimeStampTurret,
                // robotState.getTurretTimeStamp(visionTimeStampTurret),
                visionSTDMatrixTurret
            );
            didItWork = true;
        }

        if(limelightChassis.inputs.tv) {
            addVisionMeasurement(
                robotState.getChassisLimelightPose2d(),
                visionTimeStampChassis,
                visionSTDMatrixChassis
            );
            didItWork = true;
        }

        robotState.setPose2d(
            Robot.isReal() ? getState().Pose : mapleSimSwerveDrivetrain.mapleSimDrive.getSimulatedDriveTrainPose()
        );
        

        
        if(
            kP.hasChanged(kP.hashCode()) ||
            kI.hasChanged(kI.hashCode()) ||
            kD.hasChanged(kD.hashCode()) ||
            kV.hasChanged(kV.hashCode()) ||
            kA.hasChanged(kA.hashCode()) ||
            kS.hasChanged(kS.hashCode())
        ) {
            testConfigsChanged = true;
        }
        else {
            testConfigsChanged = false;
        }

        double fieldVx = 
            getState().Speeds.vxMetersPerSecond * 
            getState().Pose.getRotation().getCos() - 
            getState().Speeds.vyMetersPerSecond * 
            getState().Pose.getRotation().getSin();

        double fieldVy = 
            getState().Speeds.vxMetersPerSecond * 
            getState().Pose.getRotation().getSin() + 
            getState().Speeds.vyMetersPerSecond * 
            getState().Pose.getRotation().getCos();

        // fieldRelativeChassisSpeeds = ChassisSpeeds.fromFieldRelativeSpeeds(
        //     fieldVx,
        //     fieldVy,
        //     getState().Speeds.omegaRadiansPerSecond,
        //     getState().Pose.getRotation()
        // );
        fieldRelativeChassisSpeeds = ChassisSpeeds.fromRobotRelativeSpeeds(
            getState().Speeds.vxMetersPerSecond,
            getState().Speeds.vyMetersPerSecond,
            getState().Speeds.omegaRadiansPerSecond,
            getState().Pose.getRotation()
        );
        // Logger.recordOutput("Swerve/fieldRelativeChassisSpeeds", fieldRelativeChassisSpeeds);
        
        robotState.setChassisSpeeds(getState().Speeds, fieldRelativeChassisSpeeds);
        Logger.recordOutput("Swerve/AngularSpeeds", getState().Speeds.omegaRadiansPerSecond);

        field2d.setRobotPose(robotState.getPose2d());

        Logger.recordOutput("Drive Motor 0 kV", readConfigs.kV);
        
        Logger.recordOutput("RobotState/ChassisSpeeds/vxMetersPerSecond", robotState.getChassisSpeeds().vxMetersPerSecond);
        Logger.recordOutput("RobotState/ChassisSpeeds/vyMetersPerSecond", robotState.getChassisSpeeds().vyMetersPerSecond);
        Logger.recordOutput("RobotState/ChassisSpeeds/fieldVx", fieldVx);
        Logger.recordOutput("RobotState/ChassisSpeeds/fieldVy", fieldVy);
        Logger.recordOutput("RobotState/ChassisSpeeds/omegaRadiansPerSecond", robotState.getChassisSpeeds().omegaRadiansPerSecond);
        Logger.recordOutput("RobotState/DistanceFromHub", robotState.getDistanceFromHubMeters());

        Logger.recordOutput("RobotState/RotatedTurret", robotState.getRobotToLimelight());

        Logger.recordOutput("Swerve/didItWork???", didItWork);

        Logger.recordOutput("Pose/testConfigsChanged", testConfigsChanged);
        
        if (mapleSimSwerveDrivetrain != null && !Robot.isReal()) {
            Logger.recordOutput("Drive/SimulationPose", mapleSimSwerveDrivetrain.mapleSimDrive.getSimulatedDriveTrainPose());
        }

        testCameraPose = new Pose3d(robotState.getPose2d()).plus(new Transform3d(robotState.getRobotToLimelight().getTranslation(), robotState.getRobotToLimelight().getRotation()));

        Logger.recordOutput("Limelight Transform", testCameraPose);

        Logger.recordOutput("RobotState/ChassisSpeeds/Stator Current", this.getModule(1).getDriveMotor().getStatorCurrent().getValueAsDouble());
        Logger.recordOutput("RobotState/ChassisSpeeds/Supply Current", this.getModule(1).getDriveMotor().getSupplyCurrent().getValueAsDouble());
    }

    
    public Command setDriveGains() {
        
        return runOnce(() ->  
        {
                testConfigs.kP = kP.get();
                testConfigs.kI = kI.get();
                testConfigs.kD = kD.get();
                testConfigs.kV = kV.get();
                testConfigs.kA = kA.get();
                testConfigs.kS = kS.get();

                for (int i = 0; i < 4 ; i++) {
                    this.getModule(i).getDriveMotor().getConfigurator().apply(testConfigs);
                    this.getModule(i).getDriveMotor().getConfigurator().refresh(readConfigs);
                }

                System.out.println("Swerve Gaines Updated!");
            }
        );
    }


    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public Swerve(
        SwerveDrivetrainConstants drivetrainConstants,
        VisionTurretSubsystem turretLimelight,
        VisionChassisSubsystem chassisLimelight,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(
            drivetrainConstants, 
            Robot.isReal() ? modules : MapleSimSwerveDrivetrain.regulateModuleConstantsForSimulation(modules)
        );
        if (Utils.isSimulation()) {
            startSimThread();
        }
        this.limelightTurret = turretLimelight;
        this.limelightChassis = chassisLimelight;

        if(!Robot.isReal()){
            mapleSimSwerveDrivetrain.mapleSimDrive.setSimulationWorldPose(new Pose2d(2.5, 4, new Rotation2d()));
        }
        

        try {
            AutoBuilder.configure(
                () -> robotState.getPose2d(), // Robot pose supplier
                Robot.isReal() ? (resetPose) -> resetPose(resetPose) : (resetPose) -> mapleSimSwerveDrivetrain.mapleSimDrive.setSimulationWorldPose(resetPose), // Method to reset odometry (will be called if your auto has a starting pose)
                () -> robotState.getChassisSpeeds(), // ChassisSpeeds supplier. MUST BE ROBOT RELATIVE
                (speeds, feedforwards) -> this.setControl(new SwerveRequest.ApplyRobotSpeeds().withSpeeds(speeds)), // Method that will drive the robot given ROBOT RELATIVE ChassisSpeeds. Also optionally outputs individual module feedforwards
                new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller for holonomic drive trains
                        new PIDConstants(Constants.AutoConstants.kPDriveController, 0.0, 0.0), // Translation PID constants
                        new PIDConstants(Constants.AutoConstants.kPThetaController, 0.0, 0.0) // Rotation PID constants
                ),
                RobotConfig.fromGUISettings(), // The robot configuration
                () -> {
                    // Boolean supplier that controls when the path will be mirrored for the red alliance
                    // This will flip the path being followed to the red side of the field.
                    // THE ORIGIN WILL REMAIN ON THE BLUE SIDE

                    var alliance = DriverStation.getAlliance();
                    if (alliance.isPresent()) {
                        return alliance.get() == DriverStation.Alliance.Red;
                    }
                    return false;
                },
                this // Reference to this subsystem to set requirements
            );
        } catch (Exception e) {
            e.printStackTrace();
        } 
        


        LimelightHelpers.setCameraPose_RobotSpace(
            Constants.VisionConstants.kTurretLimelight, 
            Inches.of(-5.5 + 0).in(Meters), 
            Inches.of(7.75 + 6.58).in(Meters), 
            Inches.of(20.89).in(Meters), 
            0,
            15-1,
            90
        );

        LimelightHelpers.setCameraPose_RobotSpace(
            Constants.VisionConstants.kChassisLimelight, 
            Inches.of(-4.98 + 0).in(Meters), 
            Inches.of(-14.16).in(Meters), 
            Inches.of(13.44).in(Meters), 
            -2,
            15,
            90
        );

        SmartDashboard.putData(field2d);


    }

    /**
 * Constructs a CTRE SwerveDrivetrain using the specified constants.
 * <p>
 * This constructs the underlying hardware devices, so users should not construct
 * the devices themselves. If they need the devices, they can access them through
 * getters in the classes.
 *
 * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
 * @param odometryUpdateFrequency The frequency to run the odometry loop. If
 *                                unspecified or set to 0 Hz, this is 250 Hz on
 *                                CAN FD, and 100 Hz on CAN 2.0.
 * @param modules                 Constants for each specific module
 */
public Swerve(
    SwerveDrivetrainConstants drivetrainConstants,
    double odometryUpdateFrequency,
    SwerveModuleConstants<?, ?, ?>... modules
    ) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    if (Utils.isSimulation()) {
        startSimThread();
    }
}

/**
 * Constructs a CTRE SwerveDrivetrain using the specified constants.
 * <p>
 * This constructs the underlying hardware devices, so users should not construct
 * the devices themselves. If they need the devices, they can access them through
 * getters in the classes.
 *
 * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
 * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
 *                                  unspecified or set to 0 Hz, this is 250 Hz on
 *                                  CAN FD, and 100 Hz on CAN 2.0.
 * @param odometryStandardDeviation The standard deviation for odometry calculation
 *                                  in the form [x, y, theta]ᵀ, with units in meters
 *                                  and radians
 * @param visionStandardDeviation   The standard deviation for vision calculation
 *                                  in the form [x, y, theta]ᵀ, with units in meters
 *                                  and radians
 * @param modules                   Constants for each specific module
 */
public Swerve(
    SwerveDrivetrainConstants drivetrainConstants,
    double odometryUpdateFrequency,
    Matrix<N3, N1> odometryStandardDeviation,
    Matrix<N3, N1> visionStandardDeviation,
    SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }   


 /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }


    // private void startSimThread() {
    //     m_lastSimTime = Utils.getCurrentTimeSeconds();

    //     /* Run simulation at a faster rate so PID gains behave more reasonably */
    //     m_simNotifier = new Notifier(() -> {
    //         final double currentTime = Utils.getCurrentTimeSeconds();
    //         double deltaTime = currentTime - m_lastSimTime;
    //         m_lastSimTime = currentTime;

    //         /* use the measured time delta, get battery voltage from WPILib */
    //         updateSimState(deltaTime, RobotController.getBatteryVoltage());
    //     });
    //     m_simNotifier.startPeriodic(kSimLoopPeriod);
    // }

    public MapleSimSwerveDrivetrain mapleSimSwerveDrivetrain = null;
    
    @SuppressWarnings("unchecked")
    private void startSimThread() {
        mapleSimSwerveDrivetrain = new MapleSimSwerveDrivetrain(
                Seconds.of(kSimLoopPeriod),
                Pounds.of(115),
                Inches.of(30),
                Inches.of(30),
                DCMotor.getKrakenX60(1),
                DCMotor.getKrakenX60(1),
                1.2,
                getModuleLocations(),
                getPigeon2(),
                getModules(),
                TunerConstants.FrontLeft,
                TunerConstants.FrontRight,
                TunerConstants.BackLeft,
                TunerConstants.BackRight);
        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(mapleSimSwerveDrivetrain::update);
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }


    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
}
